/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Rtdb_CONSTANTS_H
#define Rtdb_CONSTANTS_H

#include "Rtdb_types.h"

namespace cn { namespace oge { namespace kdm { namespace rtdb { namespace thrift { namespace api {

class RtdbConstants {
 public:
  RtdbConstants();

};

extern const RtdbConstants g_Rtdb_constants;

}}}}}} // namespace

#endif
