/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Rtdb_constants.h"

namespace cn { namespace oge { namespace kdm { namespace rtdb { namespace thrift { namespace api {

const RtdbConstants g_Rtdb_constants;

RtdbConstants::RtdbConstants() {
}

}}}}}} // namespace

